version: 2.1

workflows:
  main:
    jobs:
      - run-tests



jobs:
  run-tests:
    docker:
      - image: aotuai/brainframe_build_env:0.26.0-openvino-2020
    resource_class: medium
    parallelism: 1
    steps:
      # Add pull dependencies
      - run: mkdir -m 700 ~/.ssh/ &&
             echo -e "Host *\n\tStrictHostKeyChecking no" >> ~/.ssh/config
      - run: apt update &&
             apt-get install -y ssh git git-lfs &&
             git lfs install
      # Pull the project
      - checkout
      # Install test dependencies
      - restore_cache:
          key: v1-python-cache--{{ checksum "tests/requirements.txt" }}
      - run: >
          if ! pip3 show vcap > /dev/null; then
            pip3 install --quiet -r tests/requirements.txt
          fi
      - save_cache:
          key: v1-python-cache--{{ checksum "tests/requirements.txt" }}
          paths:
            - /usr/local/lib/python3.6/
            - /usr/lib/python3.6/
            - /usr/lib/python3/
      # Run Capsule tests in multiple containers. Use circleci commands to split the test files up.
      - run: >
          circleci tests glob **/test*.py |
          circleci tests split --split-by=timings --timings-type=classname |
          xargs python3 -m pytest --junitxml=test-results/junit.xml -x -s -vvv
      - store_test_results:
          path: test-results
